SELECT H.*, S.* FROM PSAPMSGSUBCN_VW S, PSIBPUBHDR_VW H 
WHERE S.IB_OPERATIONNAME='ANU_ERMS_CREATE_FOLDER_ASYNC' 
AND S.SUBCONSTATUS <> H.PUBSTATUS -- Message not in Done status
AND S.IBPUBTRANSACTID=H.IBTRANSACTIONID
AND H.IB_OPERATIONNAME=S.IB_OPERATIONNAME
AND S.LASTUPDDTTM > DATEADD(HOUR, 2, H.LASTUPDDTTM) --Messages which were processed with a delay or resubmitted after failing
ORDER BY H.LASTUPDDTTM DESC
