SELECT * FROM PSVERSION WHERE OBJECTTYPENAME IN ('SYS','CRM')

SELECT * FROM PSCONTDEFN WHERE CONTTYPE=8 ;--AND CONTNAME LIKE 'PS_SD%'
SELECT * FROM PSCONTENT WHERE CONTTYPE=8 ;--AND CONTNAME LIKE 'PS_SD%'
SELECT * FROM PSCONTDEFNLANG WHERE CONTTYPE=8 ;--AND CONTNAME LIKE 'PS_SD%'
SELECT * FROM PSCONTENTLANG WHERE CONTTYPE=8 ;--AND CONTNAME LIKE 'PS_SD%'

/*
UPDATE PSVERSION SET VERSION=VERSION+1 WHERE OBJECTTYPENAME IN ('SYS','CRM');

DELETE FROM PSCONTDEFN WHERE CONTTYPE=8 ;
DELETE FROM PSCONTENT WHERE CONTTYPE=8 ;
DELETE FROM PSCONTDEFNLANG WHERE CONTTYPE=8 ;
DELETE FROM PSCONTENTLANG WHERE CONTTYPE=8 ;

*/
