SELECT DUR 
 , DAY_OFWEEK 
 , SCHED_HRS 
 , WRKDAY_ID 
  FROM ( 
 SELECT J.COMPANY 
 , J.GP_PAYGROUP 
 , SCH.DUR 
 , CAST(TO_CHAR(SCH.DUR 
 ,'D') AS NUMBER) - 1 DAY_OFWEEK 
 , SCH.SCHED_HRS 
 , SCH.WRKDAY_ID 
  FROM PS_JOB J 
  , PS_SCH_ASSIGN SA 
  , PS_SCH_CLND_VW SCH 
 WHERE J.EMPLID=:1 
   AND J.EMPL_RCD=:2 
   AND J.EFFDT=( 
 SELECT MAX(J1.EFFDT) 
  FROM PS_JOB J1 
 WHERE J1.EMPLID=J.EMPLID 
   AND J1.EMPL_RCD=J.EMPL_RCD 
   AND J1.EFFDT<=%DateIn(:3)) 
   AND J.EFFSEQ=( 
 SELECT MAX(J2.EFFSEQ) 
  FROM PS_JOB J2 
 WHERE J2.EMPLID=J.EMPLID 
   AND J2.EMPL_RCD=J.EMPL_RCD 
   AND J2.EFFDT=J.EFFDT) 
   AND SA.EMPLID = J.EMPLID 
   AND SA.EMPL_RCD = J.EMPL_RCD 
   AND SA.EFFDT = ( 
 SELECT MAX(SA1.EFFDT) 
  FROM PS_SCH_ASSIGN SA1 
 WHERE SA1.EMPLID = SA.EMPLID 
   AND SA1.EMPL_RCD = SA.EMPL_RCD 
   AND SA1.EFFDT <= %DateIn(:3)) 
   AND SCH.SETID=J.BUSINESS_UNIT 
   AND SCH.SCHEDULE_ID=(CASE WHEN SA.SCHEDULE_ID = ' ' THEN ( 
 SELECT PG.SCHEDULE_ID 
  FROM PS_GP_PYGRP_DTL PG 
 WHERE PG.GP_PAYGROUP=J.GP_PAYGROUP 
   AND PG.EFFDT=( 
 SELECT MAX(PG1.EFFDT) 
  FROM PS_GP_PYGRP_DTL PG1 
 WHERE PG1.GP_PAYGROUP=PG.GP_PAYGROUP 
   AND PG1.EFFDT=PG.EFFDT)) ELSE SA.SCHEDULE_ID END) 
   AND SCH.DUR BETWEEN %DateIn(:3) AND %DateIn(:3) + 13 )
