SELECT PNLFLD.PNLNAME, PNLFLD.FIELDNUM, PNLFLD.FIELDNUM, PNLFLD.OCCURSLEVEL, PNLFLD.RECNAME, PNLFLD.FIELDNAME, PNLFLD.S_RECNAME
FROM (
SELECT PNLF.PNLNAME
, ((PNLF.FIELDNUM * 1000) + COALESCE(SPNLF.FIELDNUM,0)) AS FIELDNUM
, (PNLF.OCCURSLEVEL + COALESCE(SPNLF.OCCURSLEVEL,0)) AS OCCURSLEVEL
, PNLF.RECNAME
, (CASE WHEN PNLF.FIELDNAME = ' ' THEN SPNLF.FIELDNAME ELSE PNLF.FIELDNAME END) AS FIELDNAME
, SPNLF.RECNAME AS S_RECNAME
FROM PSPNLFIELD PNLF LEFT OUTER JOIN PSPNLFIELD SPNLF ON (SPNLF.PNLNAME=PNLF.SUBPNLNAME)
) PNLFLD
WHERE PNLFLD.PNLNAME IN (SELECT PNLG.PNLNAME FROM PSPNLGROUP PNLG WHERE PNLG.PNLGRPNAME=:1)
--AND PNLFLD.FIELDNAME LIKE '%%'
ORDER BY PNLFLD.FIELDNUM
