SELECT L.PORTAL_NAME, L.PORTAL_REFTYPE, L.PORTAL_OBJNAME, L.PORTAL_PRNTOBJNAME, L.PORTAL_CREF_USGT, L.PORTAL_LINKOBJNAME
, C.PORTAL_NAME, C.PORTAL_REFTYPE, C.PORTAL_OBJNAME, C.PORTAL_PRNTOBJNAME, C.PORTAL_CREF_USGT
FROM PSPRSMDEFN L LEFT OUTER JOIN PSPRSMDEFN C ON C.PORTAL_NAME=L.PORTAL_LINK_PORTAL AND C.PORTAL_OBJNAME=L.PORTAL_LINKOBJNAME
where 1=1 
AND L.PORTAL_CREF_USGT='LINK'
AND L.PORTAL_LINKOBJNAME <> ' '
AND C.PORTAL_NAME IS NULL


SELECT LINK.PORTAL_NAME, LINK.PORTAL_REFTYPE, LINK.PORTAL_OBJNAME, LINK.PORTAL_PERMNAME, LINK.PORTAL_PERMTYPE, LINK.PORTAL_LINK_PORTAL, LINK.PORTAL_LINKOBJNAME
     , CREF.PORTAL_NAME, CREF.PORTAL_REFTYPE, CREF.PORTAL_OBJNAME, CREF.PORTAL_PERMNAME, CREF.PORTAL_PERMTYPE
FROM (SELECT L.PORTAL_NAME, L.PORTAL_REFTYPE, L.PORTAL_OBJNAME, LP.PORTAL_PERMNAME, LP.PORTAL_PERMTYPE, L.PORTAL_LINK_PORTAL, L.PORTAL_LINKOBJNAME 
FROM PSPRSMDEFN L, PSPRSMPERM LP WHERE L.PORTAL_CREF_USGT='LINK' AND L.PORTAL_LINKOBJNAME <> ' ' AND LP.PORTAL_NAME=L.PORTAL_NAME AND LP.PORTAL_OBJNAME=L.PORTAL_OBJNAME) AS LINK
LEFT OUTER JOIN (SELECT C.PORTAL_NAME, C.PORTAL_REFTYPE, C.PORTAL_OBJNAME, CP.PORTAL_PERMNAME, CP.PORTAL_PERMTYPE 
FROM PSPRSMDEFN C, PSPRSMPERM CP WHERE CP.PORTAL_NAME=C.PORTAL_NAME AND CP.PORTAL_OBJNAME=C.PORTAL_OBJNAME) AS CREF 
ON CREF.PORTAL_NAME=LINK.PORTAL_LINK_PORTAL AND CREF.PORTAL_OBJNAME=LINK.PORTAL_LINKOBJNAME AND CREF.PORTAL_PERMNAME=LINK.PORTAL_PERMNAME AND CREF.PORTAL_PERMTYPE=LINK.PORTAL_PERMTYPE
WHERE CREF.PORTAL_NAME IS NULL
