--
-- Compare Message Catalog
--
SELECT M1.MESSAGE_SET_NBR, M1.MESSAGE_NBR, M1.MESSAGE_TEXT, M1.MSG_SEVERITY, M1.DESCRLONG, M2.MESSAGE_TEXT, M2.MSG_SEVERITY, M2.DESCRLONG
, CASE WHEN M1.MESSAGE_TEXT <> M2.MESSAGE_TEXT THEN 'Changed' ELSE 'Same' END AS MSG_TXT_CHANGED
, CASE WHEN M1.MSG_SEVERITY <> M2.MSG_SEVERITY THEN 'Changed' ELSE 'Same' END AS MSG_SEVERITY_CHANGED
, CASE WHEN M1.DESCRLONG <> M2.DESCRLONG THEN 'Changed' ELSE 'Same' END AS MSG_DESCR_CHANGED
FROM PSPROJECTITEM P1, PSMSGCATDEFN M1 LEFT OUTER JOIN CSINT..PSMSGCATDEFN M2 ON M2.MESSAGE_SET_NBR = M1.MESSAGE_SET_NBR AND M2.MESSAGE_NBR = M1.MESSAGE_NBR
WHERE P1.PROJECTNAME='ANU_PUM_CS_9_2_029' AND P1.OBJECTTYPE = 25 AND P1.SOURCESTATUS IN ('2','4') AND P1.TARGETSTATUS IN ('4','5')
AND M1.MESSAGE_SET_NBR = P1.OBJECTVALUE1 AND M1.MESSAGE_NBR = P1.OBJECTVALUE2
AND M1.MESSAGE_TEXT <> M2.MESSAGE_TEXT
AND M1.MSG_SEVERITY = M2.MSG_SEVERITY
AND M1.DESCRLONG = M2.DESCRLONG


--
-- Personalisation Options
-- Define Personalizations
-- Define System Personalizations
--
SELECT * FROM PSUSEROPTNDEFN SP1 LEFT OUTER JOIN CSINT..PSUSEROPTNDEFN SP2 ON SP2.OPTN_CATEGORY_LVL = SP1.OPTN_CATEGORY_LVL AND SP2.USEROPTN = SP1.USEROPTN
WHERE SP2.LASTUPDOPRID <> 'PPLSOFT'
AND (SP2.OPTN_CATEGORY_GRP <> SP1.OPTN_CATEGORY_GRP  
OR SP2.OPTN_CATEGORY <> SP1.OPTN_CATEGORY  
OR SP2.VERSION <> SP1.VERSION  
OR SP2.DESCR <> SP1.DESCR  
OR SP2.USEROPTN_TYPE <> SP1.USEROPTN_TYPE  
OR SP2.LOCALE_BASED <> SP1.LOCALE_BASED  
OR SP2.FORMAT_CNTL <> SP1.FORMAT_CNTL  
OR SP2.FORMATLENGTH <> SP1.FORMATLENGTH 
OR SP2.FIELDNAME <> SP1.FIELDNAME  
OR SP2.RECNAME <> SP1.RECNAME
OR SP2.USER_OPTION_VALUE <> SP1.USER_OPTION_VALUE  
OR SP2.MESSAGE_SET_NBR <> SP1.MESSAGE_SET_NBR  
OR SP2.MESSAGE_NBR <> SP1.MESSAGE_NBR  
OR SP2.IMAGE_NAME <> SP1.IMAGE_NAME  
OR SP2.IMAGE_FIELD <> SP1.IMAGE_FIELD)
