--SELECT * FROM PSOPRDEFN WHERE OPRID='U1075175'
INSERT INTO PSOPRDEFN
SELECT 'U1075175', VERSION, OPRDEFNDESC, EMPLID, EMAILID, OPRCLASS, ROWSECCLASS, OPERPSWD, OPERPSWDSALT, ENCRYPTED, SYMBOLICID, LANGUAGE_CD, MULTILANG, CURRENCY_CD, LASTPSWDCHANGE, ACCTLOCK, PRCSPRFLCLS, DEFAULTNAVHP, FAILEDLOGINS, EXPENT, OPRTYPE, USERIDALIAS, LASTSIGNONDTTM, LASTUPDDTTM, LASTUPDOPRID, PTALLOWSWITCHUSER
FROM PSOPRDEFN WHERE OPRID='U4620163'
AND NOT EXISTS (SELECT 'X' FROM PSOPRDEFN WHERE OPRID='U1075175');

INSERT INTO PSROLEUSER
SELECT 'U1075175', R1.ROLENAME, R1.DYNAMIC_SW FROM PSROLEUSER R1 WHERE R1.ROLEUSER='U4620163'
AND NOT EXISTS (SELECT 'X' FROM PSROLEUSER R2 WHERE R2.ROLEUSER='U1075175' AND R2.ROLENAME=R1.ROLENAME);

--SELECT * FROM PSROLEUSER WHERE ROLEUSER='U1075175';
INSERT INTO PSROLEUSER SELECT 'U1075175','PeopleSoft Administrator','N';
 
--SELECT * FROM PSVERSION WHERE OBJECTTYPENAME IN ('UPM','SYS')
UPDATE PSVERSION SET VERSION=VERSION+1 WHERE OBJECTTYPENAME IN ('UPM','SYS');
 
--SELECT * FROM PSOPRDEFN WHERE OPRID='U1075175'
UPDATE PSOPRDEFN SET VERSION=(SELECT VERSION FROM PSVERSION WHERE OBJECTTYPENAME IN ('UPM')) WHERE OPRID='U1075175';
