--SELECT * FROM PSROLEUSER WHERE ROLEUSER='U1075175';
INSERT INTO PSROLEUSER SELECT 'U1075175','PeopleSoft Administrator','N';
 
--SELECT * FROM PSVERSION WHERE OBJECTTYPENAME IN ('UPM','SYS')
UPDATE PSVERSION SET VERSION=VERSION+1 WHERE OBJECTTYPENAME IN ('UPM','SYS');
 
--SELECT * FROM PSOPRDEFN WHERE OPRID='U1075175'
UPDATE PSOPRDEFN SET VERSION=(SELECT VERSION FROM PSVERSION WHERE OBJECTTYPENAME IN ('UPM')) WHERE OPRID='U1075175';
